version: '3'

env:
  TAG: v0.0.4

tasks:
  build:
    desc: build the CLI locally
    cmds:
      - go build .
  test:
    desc: test out the CLI
    deps:
      - build
    cmds:
      - ./test.sh
  release:
    desc: release the binary
    cmds:
      - sed -i.bak "s/$(git describe --tags --abbrev=0)/${TAG}/g" main.go
      - sed -i.bak "s/$(git describe --tags --abbrev=0)/${TAG}/g" install.sh
      - rm *.bak
      - git add -A
      - git commit -m "Bump to ${TAG}"
      - git tag -a "$TAG" -m "Version $TAG"
      - git push origin --tags
      - rm -rf dist
      - goreleaser release
